# Generated by Django 5.1.6 on 2025-02-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название страницы"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL (slug)")),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("header", "Заголовок"),
                            ("text", "Текст"),
                            ("image", "Изображение"),
                            ("list", "Список"),
                            ("link", "Ссылка"),
                        ],
                        max_length=10,
                        verbose_name="Тип блока",
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок страницы",
                "verbose_name_plural": "Блоки страниц",
                "ordering": ["order"],
            },
        ),
    ]
