# Generated by Django 5.1.6 on 2025-02-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название списка"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="uploads/", verbose_name="Изображение"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(
                default="none",
                help_text="Поддерживается HTML и Markdown",
                verbose_name="Содержимое",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="format",
            field=models.CharField(
                choices=[("html", "HTML"), ("markdown", "Markdown")],
                default="html",
                max_length=10,
                verbose_name="Формат",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL-адрес"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название страницы"
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("header", "Заголовок"),
                    ("text", "Текст"),
                    ("list", "Список"),
                    ("link", "Ссылка"),
                ],
                max_length=10,
                verbose_name="Тип блока",
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название элемента"),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Внешняя ссылка"
                    ),
                ),
                (
                    "linked_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.page",
                        verbose_name="Связанная страница",
                    ),
                ),
                (
                    "parent_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pages.menulist",
                        verbose_name="Принадлежит списку",
                    ),
                ),
            ],
        ),
    ]
