# Generated by Django 5.1.6 on 2025-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_menulist_uploadedimage_alter_page_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
