# Generated by Django 5.1.6 on 2025-02-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_menuitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(
                default="",
                help_text="Поддерживается HTML и Markdown",
                verbose_name="Содержимое",
            ),
        ),
    ]
